### ISSUE TITLE
What is the difference between you and bleve, how much difference between performance?

### ISSUE THREAD

**Issue by niyuelin1990** [go-ego/riot#11]

**Comment by orangemi** [comment]
As the author said, you should open an issue in English.

**Comment by vcaesar** [comment]
distributed, better Chinese and Pinyin search support and more features; good performance depends on the choice.

**Comment by vcaesar** [comment]
@orangemi yep.

**Comment by jpeeler** [comment]
For those curious, the title translates to [according to Google](https://translate.google.com/?um=1&ie=UTF-8&hl=en&client=tw-ob#auto/en/%E4%BD%A0%E4%BB%AC%E8%B7%9Fbleve%20%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB%EF%BC%8C%E6%80%A7%E8%83%BD%E6%9C%89%E5%A4%9A%E5%B0%91%E5%8C%BA%E5%88%AB): "What is the difference between you and bleve, how much difference between performance".

**Comment by vcaesar** [comment]
@jpeeler yep.
