### ISSUE TITLE
riot 这个项目 grpc etcd 配置有没有完整的例子 做事情能不能别三天打鱼两天晒网  

### ISSUE THREAD

**Issue by EricWJP** [go-ego/riot#118]
riot 这个项目 grpc etcd 配置有没有完整的例子 做事情能不能别三天打鱼两天晒网  
grpc 要么就直接使用 原包 你还封装一层 再使用 还没有完整的使用示例 
 是为了藏怯 
难道对每一个使用者 都要把这些代码全部 看一遍才能使用这个包 
这个开源意识太差了

**Comment by vcaesar** [comment]
The code has rarely been updated since December 2018, no one forces you to use it.
