### ISSUE TITLE
大家在提交代码时 都那么随意使用 很少有人维护的安装包  如果作者使用只有自己维护的包，能不能跟上更新？ go-vgo相关包

### ISSUE THREAD

**Issue by EricWJP** [go-ego/riot#119]
大家在提交代码时 都那么随意使用 很少有人维护的安装包  如果作者使用只有自己维护的包，能不能跟上更新？ go-vgo相关包

作者是不是再给大家挖坑？ 跳进去了 再花大量的时间跳出来？

我看了一下 如果我要使用这个包 至少要重构40% 代码？？？？

真是服了 不得不服啊

**Comment by vcaesar** [comment]
The code has rarely been updated since December 2018, no one forces you to use it.

**Comment by EricWJP** [comment]
是不是应该提出来
不是因为你分享出来 浪费了他人大量时间 就跟你没关系了
如果不在维护 基于一个开源利人的心态 是不是需要有明确提示
