### ISSUE TITLE
run simple exmaple error

### ISSUE THREAD

**Issue by zhangzhen1011** [go-ego/riot#13]
when i run the simplest_example, it shows the error below, which means cant load the dictionary.
"2017/10/30 13:48:28 载入gse词典 github.com/go-ego/riot/data/dict/dictionary.txt
2017/10/30 13:48:28 无法载入字典文件 "github.com/go-ego/riot/data/dict/dictionary.txt"

**Comment by vcaesar** [comment]
Look at your path.

**Comment by zhangzhen1011** [comment]
path is right.

**Comment by vcaesar** [comment]
Neither a relative path nor an absolute path, add your `gopath` in front.

**Comment by vcaesar** [comment]
`your gopath` + `github.com/go-ego/riot/data/dict/dictionary.txt`.

**Comment by zhangzhen1011** [comment]
problem is resolved.
need $gopath +'/src/'+'github.com/go-ego/riot/data/dict/dictionary.txt'

**Comment by vcaesar** [comment]
@zhangzhen1011 yep, you can use the deployment tool.
