### ISSUE TITLE
How to use riot for WisdomTool REST Client?

### ISSUE THREAD

**Issue by code-spring** [go-ego/riot#14]
[WisdomTool REST Client](https://github.com/wisdomtool/rest-client) supports automated testing RESTful API and automatically generating RESTful API documentation.

May need some efforts to integrate riot to[ WisdomTool REST Client](https://github.com/wisdomtool/rest-client)

**Comment by vcaesar** [comment]
Have not heard of this tool and do not need to generate automatically.

**Comment by vcaesar** [comment]
This is an advertisement.
