### ISSUE TITLE
A Newbie Question About Many CN Keywords Not Searchable in Example codelab

### ISSUE THREAD

**Issue by sgon00** [go-ego/riot#16]
Hi, I am a newbie and trying out riot. 

When I run

```
........github.com/go-ego/riot/examples/codelab]$ go run search_server.go
```

I found out many Chinese phrase (text/keywords) didn't return any results. For example, I can get results from the keywords `中` and `中国`. But when I tried `中秋`, `国庆`, `企业`, `企业家` etc., there is nothing returned. Then I tried a person name `李小龙`, and there is no result either. I also saw the target index document had the context `...... @薛蛮子:  ......`, then I tried the keyword `薛蛮子`, still no result. I don't really understand because the words `薛蛮子` is separated between two punctuation and should be easily searchable from what I feel. 

Since I am a newbie, I am wondering what causes these keywords can not return any results. The above keywords are just some examples. I tried more than that. Only small set of Chinese phrase (is that called text segmentation?) can be supported. The most keywords that I tried can not return anything. Is this due to a bad SegmenterDict dictionary.txt or project code? 

Btw I haven't read the doc and code in detail, so sorry if I am totally wrong. Thank you very much for the help. 

___My Environment:___

```
$ dep status
PROJECT                          CONSTRAINT     VERSION        REVISION  LATEST   PKGS USED
github.com/AndreasBriese/bbloom  *              branch master  28f7e88   28f7e88  1   
github.com/boltdb/bolt           *              v1.3.1         2f1ce7a   2f1ce7a  1   
github.com/dgraph-io/badger      *              v1.0.1         89689ef   89689ef  6   
github.com/dgryski/go-farm       *              branch master  e2d0fe2   e2d0fe2  1   
github.com/go-ego/cedar          *              branch master  5ebe674   5ebe674  1   
github.com/go-ego/gpy            *              branch master  66bb7e1   66bb7e1  1   
github.com/go-ego/gse            *              branch master  b16cca4   b16cca4  1   
github.com/go-ego/murmur         *              branch master  84b529b   84b529b  1   
github.com/go-ego/riot           branch master  branch master  3431598   3431598  5   
github.com/golang/protobuf       *              branch master  1643683   1643683  1   
github.com/golang/snappy         *              branch master  553a641   553a641  1   
github.com/pkg/errors            *              v0.8.0         645ef00   645ef00  1   
github.com/shirou/gopsutil       *              v2.17.10       48fc561   48fc561  2   
github.com/syndtr/goleveldb      *              branch master  549b6d6   549b6d6  12  
golang.org/x/net                 *              branch master  a337091   a337091  3   
golang.org/x/sys                 *              branch master  75813c6   4b45465  2
```

**Comment by vcaesar** [comment]
Look at the updated example, did not update the word segmentation rules.

**Comment by sgon00** [comment]
PS: I tried to see how much memory would the simplest example use. That surprised me too. `simple/zh/main.go` took about ___314MB___ memory and `simple/main.go` took ___134MB___ memory. Is this expected behavior? At least, it's not what I expected. Thanks a lot for your help.

**Comment by vcaesar** [comment]
Disk version is still in progress, the current version of the index in memory.

**Comment by sgon00** [comment]
Thank you very much for your reply. I am a newbie in searching technique. `simple/zh/main.go` only has three index documents and `dictionary.txt` is only 8.9M. Even if it's _314MB_ on ssd/harddisk, I still think that is too large. I might be totally wrong. Is this large size of storage usage expected behavior in general full-text search engine? I haven't used any full-text search engine before, so I have no idea about it. 
Btw, are you going to use `badger` for disk version? Thanks a lot.

**Comment by vcaesar** [comment]
Use badger, bolt and leveldb.
