### ISSUE TITLE
[SUGGEST] About vendor

### ISSUE THREAD

**Issue by szyhf** [go-ego/riot#26]
## Not sure

Just wondering why to keep all third lib source code in vendor directory?  That case some dependence issue in my workspace, I think keep the `vendor.json` is enough ?  Source code make the repo larger and keep extra source in project vendor.

What I use is `glide` to config my project, I think it work well and recommend to you ~

**Comment by szyhf** [comment]
I made a glide version on my fork and you may take a look ~

https://github.com/szyhf/go-riot/tree/glide

**Comment by vcaesar** [comment]
Thank you for your suggestion, there is no plan to migrate, intend to migrate to `dep` later.

**Comment by szyhf** [comment]
Understanding, that's ok~
