### ISSUE TITLE
Q: handling unpredictable schema

### ISSUE THREAD

**Issue by ivanjaros** [go-ego/riot#30]
Hi,
I have a use case where each object can and will have completely different fields(and data types). So I cannot create schema that the search server can use to index this data in advance.

With elasticsearch I would have to create basically new index for every object which would be a nightmare, or translate each field into flat key/value structure and have a global index of these without a lot of features that would be otherwise available(facets, range search..).

Can riot handle such use case?

**Comment by vcaesar** [comment]
Riot currently indexes based on the `Content`, the `Tokens`, and the score fields, `types.DocIndexData{Content: "test, in the way", Tokens: tokenDatas, Fields: "way"}`.
