### ISSUE TITLE
Example returns no results

### ISSUE THREAD

**Issue by MintyOwl** [go-ego/riot#4]
This is the output
```
2017/10/23 15:41:30 Check virtualMemory...
Total: 8551211008, Free:0, UsedPercent:44.000000%
2017/10/23 15:41:30 {[google testing] [] false 0}
```
I dont think this is the right output.

**Comment by vcaesar** [comment]
The default is from `google` and `testing` two words and conditional search.

**Comment by vcaesar** [comment]
The example has been fixed and the word segmentation rules will be adjusted.

**Comment by MintyOwl** [comment]
Nice there. Hope more docs will be added!
