### ISSUE TITLE
[Question or PR] Can tow engine share the same segmenter at the same time?

### ISSUE THREAD

**Issue by szyhf** [go-ego/riot#51]
## Description
For some reason I have to use more than one engine at the same process, but while init each engine have to load the dictionary for segment, that cost a lot of time and memory, if I share the segmenter for different engine, will that case the concurrent problem?

If it can be done, may I make a PR for this engine option?
...

**Comment by szyhf** [comment]
Looks like the `opt.NotUseGse` can't work properly while use storage.

load storage will call innerIndexDoc and send doc to segment chan.

**Comment by vcaesar** [comment]
Welcome to optimization, I will test it.

**Comment by szyhf** [comment]
All right, I'll try

**Comment by szyhf** [comment]
@vcaesar By the way, really a pleasure to see the updating of deb

**Comment by szyhf** [comment]
@vcaesar quite busy in past days, and our project fix the share with a temp solution, since the segmenter has a complex struct/interface and by your design I felt that you want keep the config simple.

I'm wondering using some design like what gRPC using in `callOption`\`dialOption` to inject the complex implement like below: 
```
// NewServer creates a gRPC server which has no service registered and has not
// started to accept requests yet.
func NewServer(opt ...ServerOption) *Server {
    //
}
```

What I Image the implement may look like: 
```
type Optioner interface{
  // not designed yet
}
func (engine *Engine) Init(options types.EngineOpts, otherOpts ... Optioner ){

}
```
```
opt := types.EngineOpts{
//...
}
seg := mySeg{} // implement a `Optioner` interface
sthComplexToo := sth{} // implement a `Optioner` interface, too, may be the self imp storager
this.riotEngine = new(riot.Engine)
riotEngine.Init(opt,seg,sthComplexToo)
```

What's your opinion? My first target is to stripping the segmenter and second is the storager.

**Comment by vcaesar** [comment]
Thanks for your tips and contributions, but I have a better solution, please see the [code](807ca0b3642fabd2c171ef7c0a111baa276e7042).

**Comment by szyhf** [comment]
@vcaesar Great ~
