### ISSUE TITLE
Vendoring std net lib causes panic  in unvedored applications

### ISSUE THREAD

**Issue by ikozinov** [go-ego/riot#57]
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x1681840, 0xf9da88, 0xf, 0x16275a0, 0xfdc2e0)
	/usr/local/go/src/net/http/server.go:2270 +0x627
net/http.(*ServeMux).HandleFunc(0x1681840, 0xf9da88, 0xf, 0xfdc2e0)
	/usr/local/go/src/net/http/server.go:2302 +0x55
net/http.HandleFunc(0xf9da88, 0xf, 0xfdc2e0)
	/usr/local/go/src/net/http/server.go:2314 +0x4b
github.com/go-ego/riot/vendor/golang.org/x/net/trace.init.0()
	/home/ivk/go/src/github.com/go-ego/riot/vendor/golang.org/x/net/trace/trace.go:115 +0x42
github.com/go-ego/riot/vendor/golang.org/x/net/trace.init()
	<autogenerated>:1 +0x1cd
github.com/go-ego/riot/vendor/github.com/dgraph-io/badger.init()
	<autogenerated>:1 +0x78
github.com/go-ego/riot/storage.init()

-----------------
This problem resolving very simple -- removing "net" dependency from:
Gopkg.toml.

#[[constraint]]
#  branch = "master"
#  name = "golang.org/x/net"

**Comment by vcaesar** [comment]
Thanks, i will check it and update it.

**Comment by vcaesar** [comment]
I updated the vendor, and tested Stroe, no error, if the error persists, please tell me how to reproduce it.
