### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [go-ego/riot#59]
Hi,, i'm graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard. Mirza zulfan.

**Comment by vcaesar** [comment]
Thanks, and welcome contributions.

**Comment by mirzazulfan** [comment]
Hi sir @vcaesar .. i've designed a logo, tell me if you need some change i'll fix it. if you have an idea please share with me, it would be better for me. if you like it i'll send you files and pr. thank you. 
![riot v1](https://user-images.githubusercontent.com/36124339/42200959-e35c3cec-7ebf-11e8-832e-4024f8b6d68a.png)

**Comment by vcaesar** [comment]
It looks good, I think the monochrome logo should have blue and black, can it be more scientific and fluid? I think this can look like `Go` language, and it is a "R" that flips over. You can optimize it in detail, the color logo can be divided into three colors. Thank you again. 
![m2_m_1](https://user-images.githubusercontent.com/16043470/42226696-35459f2e-7f12-11e8-987c-ce791ce6300f.png)

**Comment by vcaesar** [comment]
I just think that this design has more meaning, I paint very poorly, please adjust the details or give suggestions.

**Comment by mirzazulfan** [comment]
Ok sir. i'll make it soon. thanks for your feedback.

**Comment by mirzazulfan** [comment]
how about this sir @vcaesar ? 
![v3](https://user-images.githubusercontent.com/36124339/42237362-be2d49d0-7f27-11e8-892a-dee4a06f4815.png)
waiting your feedback?

**Comment by vcaesar** [comment]
I think the third is better, you can give me a PR. 
The color is very dark, I can adjust the color myself.

**Comment by mirzazulfan** [comment]
You mean like this sir ? ok. I'll sent you a Pr.
![512px](https://user-images.githubusercontent.com/36124339/42288611-a722fb54-7fe5-11e8-9a01-a61c5b857dfe.png)

**Comment by mirzazulfan** [comment]
I uploaded the files and updated the readme file. You can get the other version in [Gdrive](https://drive.google.com/drive/folders/1YsbgXp_5FT6vfqFM5SwENvo8XHwqweN4?ogsrc=32)
Here's the pr #61 . Thanks a lot sir @vcaesar 
Best regards.
