### ISSUE TITLE
How do i update a index?

### ISSUE THREAD

**Issue by jiankuny** [go-ego/riot#65]
#19
can i use
RemoveDoc(id, forceUpdate)
and then
Index(id, types.DocData{Content: title,},forceUpdate)

is that thread safe?

**Comment by vcaesar** [comment]
Index addition and deletion operations are thread safe.

**Comment by vcaesar** [comment]
What do you express by calling the function call? This is obviously a bug. Closing is due to duplicate ( #19 ) and non-issue regulations.
