### ISSUE TITLE
有没有计划增加 GEOM索引

### ISSUE THREAD

**Issue by lujieha** [go-ego/riot#71]
1. Please **speak English**, this is the language everybody of us can speak and write.
2. Please take a moment to search that an issue **doesn't already exist**.
3. Please ask questions or config/deploy problems on our Gitter channel: https://gitter.im/go-ego/ego
4. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Ego version (or commit ref):
- Go version:
- Gcc version:
- Operating system and bit:
- Can you reproduce the bug at [Examples](https://github.com/go-ego/riot/tree/master/examples):
  - [ ] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:
 
```Go

```
- Log gist:

## Description

...

**Comment by vcaesar** [comment]
This feature is in the plan, closing is due to duplicate ( #58 ).
